name: Build site index
on:
  pull_request:
    types: [opened, synchronize, labeled]
    paths-ignore:
      - 'index.html'

jobs:
  build:
    name: site build

    runs-on: ubuntu-latest

    steps:
    - name: set variables
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: vars
    - uses: actions/checkout@v1

    - name: Set up Go 1.17
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
      id: go

    - name: Build site index
      run: |
        go run ./script/build_site.go

    - name: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git commit -m "update site"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ steps.vars.outputs.branch }}
